package com.mycompany.projetomat;

import java.awt.Color;
import javax.swing.JOptionPane;

public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaCalculos
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelDesktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuCalculos = new javax.swing.JMenuItem();
        mnuLimparJanelas = new javax.swing.JMenuItem();
        mnuSair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuVersao = new javax.swing.JMenuItem();
        informacoes = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Protótipo para Cálculo de Área de Tronco de uma Pirâmide");
        setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        PanelDesktop.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout PanelDesktopLayout = new javax.swing.GroupLayout(PanelDesktop);
        PanelDesktop.setLayout(PanelDesktopLayout);
        PanelDesktopLayout.setHorizontalGroup(
            PanelDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );
        PanelDesktopLayout.setVerticalGroup(
            PanelDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 296, Short.MAX_VALUE)
        );

        jMenu1.setText("Opções");

        mnuCalculos.setText("Cálculos");
        mnuCalculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCalculosActionPerformed(evt);
            }
        });
        jMenu1.add(mnuCalculos);

        mnuLimparJanelas.setText("Limpar Caixas");
        mnuLimparJanelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLimparJanelasActionPerformed(evt);
            }
        });
        jMenu1.add(mnuLimparJanelas);

        mnuSair.setText("Sair");
        mnuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSairActionPerformed(evt);
            }
        });
        jMenu1.add(mnuSair);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Sobre");

        mnuVersao.setText("Versão");
        mnuVersao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVersaoActionPerformed(evt);
            }
        });
        jMenu2.add(mnuVersao);

        informacoes.setText("Informações");
        informacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                informacoesActionPerformed(evt);
            }
        });
        jMenu2.add(informacoes);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelDesktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelDesktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void mnuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuSairActionPerformed

    private void mnuVersaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVersaoActionPerformed
         JOptionPane.showMessageDialog(rootPane, "0.1 - Tronco de Pirâmide\nCódigo: Gusta024092\nDesign e revisão: Machado-Leandro11\nUso Livre", "Versão da Aplicação", JOptionPane.OK_OPTION);
    }//GEN-LAST:event_mnuVersaoActionPerformed

    private void informacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_informacoesActionPerformed
        informaCalculos frame = new informaCalculos();
        frame.setVisible(true);
        frame.setSize(1024, 600);
        PanelDesktop.add(frame);
        
    }//GEN-LAST:event_informacoesActionPerformed

    private void mnuCalculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCalculosActionPerformed
        Calculos frame = new Calculos();
        frame.setVisible(true);
        frame.setSize(1024, 600);
        PanelDesktop.add(frame);
    }//GEN-LAST:event_mnuCalculosActionPerformed

    private void mnuLimparJanelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLimparJanelasActionPerformed
        PanelDesktop.removeAll();
        PanelDesktop.revalidate();
        PanelDesktop.repaint();
    }//GEN-LAST:event_mnuLimparJanelasActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane PanelDesktop;
    private javax.swing.JMenuItem informacoes;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnuCalculos;
    private javax.swing.JMenuItem mnuLimparJanelas;
    private javax.swing.JMenuItem mnuSair;
    private javax.swing.JMenuItem mnuVersao;
    // End of variables declaration//GEN-END:variables
}
